# Generated by tapster on 2026-09-20T02:22:36.741902Z
class Flit < Formula
  desc "AI-powered Conventional Commits Generator"
  homepage "https://github.com/CalsRanna/auto_commit"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_commit/releases/download/v1.0.16/flit-macos"
    sha256 "1b6ae4c43f3717c083ef1b833e768daf1f2f21f24e94c5593859b1613a2f2205"
  else
    url "https://github.com/CalsRanna/auto_commit/releases/download/v1.0.16/flit-linux"
    sha256 "33d5142a9d073a102cfcd84207827ab1f8622392ea2f4fb733cf4f475b2d6a27"
  end

  license "MIT"

  

  def install
    if OS.mac?
      bin.install "flit-macos" => "flit"
    else
      bin.install "flit-linux" => "flit"
    end

  end

  test do
    system "#{bin}/flit", "--version"
  end
end
