# Generated by tapster on 2026-09-20T04:06:31.215530Z
class Flit < Formula
  desc "AI-powered Conventional Commits Generator"
  homepage "https://github.com/CalsRanna/auto_commit"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_commit/releases/download/v1.0.17/flit-macos"
    sha256 "736a447dcf0350931a6d86d5f0bd281c8ee40da50043b69131619774c55f07a1"
  else
    url "https://github.com/CalsRanna/auto_commit/releases/download/v1.0.17/flit-linux"
    sha256 "81688f91571765c7cc31ceefbaadc9b669188d19cabc076db93274a8782ed461"
  end

  license "MIT"

  

  def install
    if OS.mac?
      bin.install "flit-macos" => "flit"
    else
      bin.install "flit-linux" => "flit"
    end

  end

  test do
    system "#{bin}/flit", "--version"
  end
end
