# Generated by tapster on 2026-09-20T01:31:40.077201Z
class Journal < Formula
  desc "Automatic Git work log generator with AI analysis."
  homepage "https://github.com/CalsRanna/auto_reflect"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.4/journal-macos"
    sha256 "5887ebae1ee60066cee026288773f61c091162cb862d810fb4c2f7b226f2035a"
  else
    url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.4/journal-linux"
    sha256 "36a3cb29701ac1cf189d15869b1e655c7d8ce0a924d6265722a786c27ad28038"
  end

  license "MIT"

  

  def install
    if OS.mac?
      bin.install "journal-macos" => "journal"
    else
      bin.install "journal-linux" => "journal"
    end

  end

  test do
    system "#{bin}/journal", "--version"
  end
end
