# Generated by tapster on 2026-10-08T10:13:10.629597Z
class Journal < Formula
  desc "Automatic Git work log generator with AI analysis."
  homepage "https://github.com/CalsRanna/auto_reflect"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.6/journal-macos"
    sha256 "e2a2c4316dd367a529821122c35cc4d14347c1fdea12b57da398880208df0708"
  else
    url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.6/journal-linux"
    sha256 "0769c2798e34b62a9877973d17fdfc2ea8bb544a04fb60e25754faec8513db6f"
  end

  license "MIT"

  

  def install
    if OS.mac?
      bin.install "journal-macos" => "journal"
    else
      bin.install "journal-linux" => "journal"
    end

  end

  test do
    system "#{bin}/journal", "--version"
  end
end
