# Generated by tapster on 2026-09-20T03:31:19.350269Z
class Journal < Formula
  desc "Automatic Git work log generator with AI analysis."
  homepage "https://github.com/CalsRanna/auto_reflect"
  if OS.mac?
    url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.5/journal-macos"
    sha256 "42e3a92b0166ba9400f1a56593af24143726dc76c06253066ebcaefa3ba94494"
  else
    url "https://github.com/CalsRanna/auto_reflect/releases/download/v2.3.5/journal-linux"
    sha256 "978ec54c7e75049e6fe711cebf136a49da39266a08da9c6e07794ff01373ea6b"
  end

  license "MIT"

  

  def install
    if OS.mac?
      bin.install "journal-macos" => "journal"
    else
      bin.install "journal-linux" => "journal"
    end

  end

  test do
    system "#{bin}/journal", "--version"
  end
end
